#!/usr/bin/env bash

# Install native apps
run_apps() {
	# utils
	brew cask install adobe-creative-cloud
	brew cask install dropbox
	brew cask install firefox
	brew cask install google-chrome
	brew cask install the-unarchiver
	brew cask install slack
	brew cask install spotify
	brew cask install typora
	brew cask install vlc

	# dev
	brew cask install coderunner
	brew cask install docker
	brew cask install github
	brew cask install gitkraken
	brew cask install graphql-playground
	brew cask install insomnia
	brew cask install hyper
	brew cask install imageoptim
	brew cask install ksdiff # Kaleidoscope command line
	brew cask install kitematic
	brew cask install now
	brew cask install pngyu
	brew cask install postman
	brew cask install virtualbox
	brew cask install visual-studio-code
}
